// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface FeeCalculator$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "FeeCalculator";
  readonly sourceName: "contracts/libraries/FeeCalculator.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"fee","type":"uint256"}],"name":"FeeTooHigh","type":"error"},{"inputs":[{"internalType":"uint256","name":"percentage","type":"uint256"}],"name":"InvalidPercentage","type":"error"}];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220191eef88ba496f45f1b11d31388ebb94771f7fd08b296ba56028286a49cf1ef364736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220191eef88ba496f45f1b11d31388ebb94771f7fd08b296ba56028286a49cf1ef364736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/FeeCalculator.sol";
  readonly buildInfoId: "solc-0_8_28-a5f908ff89c8350670d816f7824223e212c1e0e2";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["FeeCalculator"]: FeeCalculator$Type;
    ["contracts/libraries/FeeCalculator.sol:FeeCalculator"]: FeeCalculator$Type;
  }
}