const routes = {
  home: '/',
  minimal: '/minimal',
  livePricing: '/live-pricing',
  retro: '/retro',
  swap: '/swap',
  liquidity: '/liquidity',
  liquidityPosition: '/liquidity-position',
  farms: '/farms',
  createNft: '/create-nft',
  nftDetails: '/nft-details',
  search: '/search',
  notification: '/notifications',
  vote: '/vote',
  proposals: '/proposals',
  createProposal: '/proposals/create',
  charts: '/charts',
  profile: '/profile',
  portfolio: '/profile?view=portfolio',
  history: '/profile?view=history',
  classic: '/classic',
  coinDetails: '/coin-details',
  signIn: '/authentication',
  signUp: '/authentication/sign-up',
  resetPin: '/authentication/reset-pin',
  forgetPassword: '/authentication/forget-password',
  tradingBot: '/trading-bot',
  tradingBotSpotGrid: '/spot-grid-bot',
  tradingBotFuturesGrid: '/futures-grid-bot',
  tradingBotMartingale: '/martingale-bot',
  tradingBotInfinityGrid: '/infinity-grid-bot',
  pages: '/pages',
  
  // CrowdVC routes
  pitches: '/pitches',
  pools: '/pools',
  voting: '/voting',
  submitPitch: '/submit',
  submitDeck: '/submit/deck',
  submitVideo: '/submit/video',
  submitDetails: '/submit/details',
  managePitches: '/manage',
  managePending: '/manage/pending',
  manageApproved: '/manage/approved',
  manageInPools: '/manage/pools',
  fundingStatus: '/funding',
  fundingActive: '/funding/active',
  fundingCompleted: '/funding/completed',
  fundingPayouts: '/funding/payouts',
  admin: '/admin',
  adminPitches: '/admin/pitches',
  adminPools: '/admin/pools',
  adminUsers: '/admin/users',
  adminAnalytics: '/admin/analytics',
};

export default routes;
