const routes = {
  home: "/",
  minimal: "/minimal",
  livePricing: "/live-pricing",
  retro: "/retro",
  swap: "/swap",
  liquidity: "/liquidity",
  liquidityPosition: "/liquidity-position",
  farms: "/farms",
  createNft: "/create-nft",
  nftDetails: "/nft-details",
  search: "/search",
  notification: "/notifications",
  vote: "/vote",
  proposals: "/proposals",
  createProposal: "/proposals/create",
  charts: "/charts",
  profile: "/profile",
  portfolio: "/profile?view=portfolio",
  history: "/profile?view=history",
  classic: "/classic",
  coinDetails: "/coin-details",
  signIn: "/authentication",
  signUp: "/authentication/sign-up",
  resetPin: "/authentication/reset-pin",
  forgetPassword: "/authentication/forget-password",
  tradingBot: "/trading-bot",
  tradingBotSpotGrid: "/spot-grid-bot",
  tradingBotFuturesGrid: "/futures-grid-bot",
  tradingBotMartingale: "/martingale-bot",
  tradingBotInfinityGrid: "/infinity-grid-bot",
  pages: "/pages",

  // CrowdVC routes
  pitches: "/dashboard/pitches",
  pitchDetails: "/dashboard/pitches/[id]",
  pools: "/dashboard/pools",
  voting: "/dashboard/voting",
  submitPitch: "/dashboard/pitches/submit-pitch",
  submitDeck: "/dashboard/submit/deck",
  submitVideo: "/dashboard/submit/video",
  submitDetails: "/dashboard/submit/details",
  managePitches: "/dashboard/manage",
  managePending: "/dashboard/manage/pending",
  manageApproved: "/dashboard/manage/approved",
  manageInPools: "/dashboard/manage/pools",
  fundingStatus: "/dashboard/funding",
  fundingActive: "/dashboard/funding/active",
  fundingCompleted: "/dashboard/funding/completed",
  fundingPayouts: "/dashboard/funding/payouts",
  admin: "/dashboard/admin",
  adminPitches: "/dashboard/admin/pitches",
  adminPools: "/dashboard/admin/pools",
  adminUsers: "/dashboard/admin/users",
  adminAnalytics: "/dashboard/admin/analytics",
};

export default routes;
